baseURL: "https://paragjadhav.netlify.app/"
languageCode: "en-us"
title: "Parag Jadhav | Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"
  
enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: https://cdn2.iconfinder.com/data/icons/inclusiveness-vivid-vol-2/256/Scientist-male-512.png
  description: "Parag's personal portfolio"

  # Navbar Menus
  

  # home
  disable_home: false
  profile_image: /images/profile.png
  name: "Parag Jadhav"
  namecolor: ffc107
  profession: "Data Scientist and Data Analyst @Digital Charging Solutions GmbH"
  github: "https://github.com/paragj30/"
  linkedin: "https://www.linkedin.com/in/parag-jadhav-429026146/"
  twitter: "https://twitter.com/ParagJa44/"
  gmail: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=paragj30@gmail.com"
  instagram: "https://www.instagram.com/dungeon_master14?utm_medium=copy_link"
  

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=paragj30@gmail.com"
      fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=paragj30@gmail.com"

  # About
  disable_about: false  
  descripe_l1_person: "Hi there! Myself Parag and currently working at Digital Charging Solutions Gmbh as Data Analyst Intern. I am very passionate about evergrowing technology especially in the field of DataScience and MLOps…. With a deep passion for Machine Learning (ML), Deep Learning (DL), and MLOps, I am an accomplished engineer skilled in harnessing the power of modern web technologies to build exceptional DS projects. My expertise extends beyond aesthetics and functionality; I have a comprehensive understanding of ML and DL algorithms, frameworks, and techniques that enable me to create intelligent systems capable of analyzing vast amounts of data and delivering accurate predictions."
  descripe_l2_person: "### Real world capabilities"
  descripe_l3_person: "I excel at designing and implementing robust ML infrastructure and automation pipelines. I leverage state-of-the-art tools and frameworks such as Docker, Kubernetes, git actions, etc. to optimise workflows, ensuring the scalability and reproducibility of ML processes. My hard skills include: Python, SQL, MachineLearning, DL, NLP and others. My ability to seamlessly integrate ML solutions into existing systems empowers organisations to embrace the full potential of their data, gaining a competitive edge in today’s rapidly evolving market. If you are seeking a skilled ML/DL engineer and MLOps expert who can deliver exceptional results, I am confident in my ability to drive your organisation’s success through innovative technologies. and data-driven solutions. Let’s collaborate and unlock the power of ML and DL for your business."
  descripe_l4_person: "*You can find my works [here](#projects)* "

  skills:
    - name: Python3
      percentage: 80
    - name: Object Orient Programming (OOPS)
      percentage: 75
    - name: "SQL"
      percentage: 80
    - name: "HTML"
      percentage: 60
    - name: "Machine Learning"
      percentage: 90
    - name: "Deep Learning"
      percentage: 75
    - name: "NLP"
      percentage: 76
    - name: "Backend Engineering"
      percentage: 90
    - name: "Flask"
      percentage: 80
    - name: "Azure, AWS, Heroku"
      percentage: 80
    - name: "ML-operations"
      percentage: 70
    - name: CI/CD pipelines
      percentage: 70
    - name: Cloud Deployment automation
      percentage: 80
    - name: Dockers
      percentage: 80
    - name: Kubernetes
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Digital-Charging-Solutions-Gmbh"
      role: "Data Analyst Intern"
      startdate: "Nov 2023"
      enddate: "Ongoing"
      featuredpoints:
        - point: "Build the automated SQL script which is used to send particular data from the Snowflake database and integrated it to a PowerBI where all operations can be made easily."
        - point: "Extract the insights from the data and understand the problems related to the data."
        - point: "Manage and extract the required data from the snowflake using SQL and the Dbt GUI"
        - point: "Create machine learning models for Customer segmentation, Sentiment Analysis, etc. for better customer experience and operational excellence using Python"
        - point: "Develop dashboards and reports using Power BI and Power Query with MS Excel"
        - point: "Work on SQL Server Management for monthly reports."
        - point: "Support different departments like KAM, Pricing, and Revenue for Ad Hoc analysis reports using SQL, and Python."
        - point: "Identify and build Machine Learning use cases for a better understanding of market take rate using time series analysis."
        - point: "Communicate with different team members, like internal and external stakeholders."
        - point: "Conduct research and stayed current with the latest technologies and developments in EV charging."
        - point: "Demonstrate a commitment to quality, innovation, and continuous learning through an innovative approach to problem-solving."
        - point: "Collaborate with cross-functional teams to design end-to-end solutions, including data engineers and data scientists."
    - company: "Unicom-Infotel"
      role: "Sr. Executive (Data Science Dept.)"
      startdate: "Feb 2019"
      enddate: "Mar 2022"
      featuredpoints:
        - point: "As the Data Scientist at Unicom Infotel from February 2019 to March 2022, I was part of system development, focusing on building state-of-the-art (SOTA) ML pipelines."
        - point: "My expertise spans a wide range of areas, including working extensively with ML models such as supervised models, implementing stable models, and ensuring seamless deployment of ML systems."
        - point: "I was dedicated to driving innovation, operational excellence, and tangible business outcomes through ML and DL engineering coupled with MLOps practices."
        - point: "Built the automated Python script which is used to send particular data from the database and integrated it to a frontend where all operations can be made easily."
        - point: "Solve a use case on Industry level end to end machine learning project."
        - point: "ML/DL project domain was concerning health and insurance."
        - point: "Used MLOPS(DVC pipeline) for building and deploying the model."
        - point: "Built CI/CD pipeline."
        - point: "Used Flask API as a backend."
        - point: "Used GitHub actions for automatic build and deploy of the model."
        - point: "Hosted to cloud environments like Azure, AWS, and Heroku platform."        
    - company: "ITSource"
      role: "Trainee Engineering - (ML Dept.)"
      startdate: Jul 2018
      enddate: Feb 2019
      featuredpoints:
        - point: "Learnt ML, NLP and DL from Scratch."
        - point: "Learnt to build neural networks using ANN, CNN, etc."
        - point: "Built numerous types of projects by using different ML and DL algorithms."
        - point: "Learnt Python programming from basics to classes, objects, OOPS."
        - point: "Learnt libraries like NumPy, pandas, matplotlib, seaborn, and plotly."
  
  #certifications section
  disable_certification: false
  certification:
    - Name: ESG-Hackathon-with-Integration-Alpha
      institution: Integration Alpha Swiss based FinTechs in collaboration with Gisma University of Applied Sciences
      startdate: "Nov 2022"
      enddate: "Lifetime"
      link:
        - weblink: "https://drive.google.com/file/d/1F7WwW-eHe21C4JEhjlNwvt12msPclH_n/view?usp=drive_link"
          certificate: "View Certificate"
    - Name: Build-your-own-Movie-Recommendation-System-using-Pandas-Bootcamp
      institution: Opean Weaver
      startdate: "Oct 2022"
      link:
        - weblink: "https://certificates.openweaver.com/en/verify/99483015708982?ref=email"
          certificate: "View Certificate"
    - Name: Breast-Cancer-Prediction-using-SVM-Bootcamp
      institution: Opean Weaver
      startdate: "Oct 2022"
      link:
        - weblink: "https://certificates.openweaver.com/en/verify/93633251980853?ref=email"
          certificate: "View Certificate"
    - Name: Build-AI-Fake-News-Detection-Online-Bootcamp
      institution: Opean Weaver
      startdate: "Oct 2022"
      link:
        - weblink: "https://certificates.openweaver.com/en/verify/61996276600573?ref=email"
          certificate: "View Certificate"
    - Name: Data-Analytics
      institution: Jobaaj
      startdate: "Oct 2022"
      link:
        - weblink: "https://www.jobaajlearnings.com/certificate?file=1665729392_17215.jpeg"
          certificate: "View Certificate"
    - Name: Basics-of-Python-Programming-for-Absolute-Beginners-Bootcamp
      institution: Opean Weaver
      startdate: "Oct 2022"
      link:
        - weblink: "https://certificates.openweaver.com/en/verify/17408872439614?ref=email"
          certificate: "View Certificate"
    
      
  # Education
  disable_education: false
  education:
    - degree: "MSc Data Science, AI, and Digital Business"
      branch: "Data Science"
      university: "GISMA University of Applied Science, Potsdam, Germany"
     
      startedyear: "2022"
      graduation: "2023"
    - degree: "B.E- Electronics and Telecommuncation"
      branch: "Electronics and Telecommuncation"
      university: "International Institute of Information Technology, Pune, India"
      startedyear: "2015"
      graduation: "2018"
    - degree: "Diploma- Electronics and Communication"
      university: "Dr. D. Y. Patil University, Navi Mumbai, India"
      startedyear: "2012"
      graduation: "2015"
    - degree: "Class X"
      university: "Dr. Bedekar Vidya Mandir, Thane, India"
      startedyear: "2012"

  # Projects
  disable_projects: false
  projects:
    - name: "red wine quality prediction(POC)"
      img: /images/redwine.jpg
      githublink: "https://github.com/paragj30/red_wine_quality_prediction"
      featuredlink: ""
      description: "This project focuses on predicting the quality of red wine using a regression model based on various chemical properties. The dataset, sourced from Kaggle, contains multiple features that describe the characteristics of red wine samples. The primary objective is to build a model that can accurately predict the quality of wine, which is rated on a scale from 0 to 10, using these features."
    - name: "End to End Car Price Predication"
      img: /images/car_price.jpg
      githublink: "https://github.com/paragj30/car_price_prediction_end_to_end/"
      description: "Our client is a startup, aims to streamline the process of pricing vehicles by implementing a machine learning-based system. Initially, sales representatives gather information from clients, which is then analyzed to predict the car's price. To automate and improve this process, they plan to develop a website where users can input car details, and a machine learning algorithm will predict the price based on features like brand, model, year, fuel type, horsepower, etc. The model will use regression algorithms to analyze patterns in the dataset and make accurate price predictions for new inputs. I Developed a ML model starting from Data ingestion, data preprocessing, EDA, feature engineering, model training, model evaluations, model pickeling, create app.py using flask, delpoyement of model, creating a docker image, deployment of docker image on Docker Hub, and pull the docker image in the host system and createda a CI-CD pipeline."
    - name: "Consumer Complaint Sentimental Analysis Using NLP"
      img: /images/progress.png
      githublink: "https://github.com/paragj30/Sentiment-Analysis-using-e-commerce-data/"
      featuredlink: ""
      description: "Our client was a prominent US-based E-commerce marketplace, started as an online bookstore before diversifying its product range. They noticed a decline in product evaluations and a mix of positive and negative comments from customers worldwide. I perform pre-dataprocessing using NLP technique on customer feedback, particularly from reviews in multiple languages like English, German, Spanish, French, Japanese, and Chinese. A language detection algorithm was used to filter reviews, and unsupervised machine learning to predict sentiment classes (Positive/Negative/Neutral) for each review."
    - name: "Consumer Churn Detection using Artifical Neural Networks (ANN)"
      img: /images/bank_churn.jpg
      githublink: "https://github.com/paragj30/Churn_Detection_ANN"
      description: "Our client was a prominent Indian financial institution, caters to various customer segments and aims to predict customer churn to prioritize retention efforts. They plan to use demographic and attribute data to identify customers at risk of leaving. Our experts gathered insights to design a machine learning pipeline focusing on forecasting customer churn. The independent variables describing customer attributes and a dependent variable indicating customer desertion. Factors like credit score, age, tenure, balance, and product ownership are considered relevant predictors of churn. The bank's objective is to maximize recall by accurately identifying customers likely to leave, given the dataset's imbalance. This approach aims to optimize retention efforts and minimize customer attrition."
    - name: "Grocery Image Multiclassification using Convolution Neural Networks(CNN) Deep learning"
      img: /images/grocery_class.jpg
      githublink: "https://github.com/paragj30/CNN/blob/main/freiburg_CNN_Image%20classification.ipynb"
      description: "Grocery Image Classification Project, covering various aspects of the project lifecycle. A Convolutional Neural Network (CNN) is a deep learning algorithm designed specifically for image recognition tasks. I created multiple layers, including convolutional layers, pooling layers, and fully connected layers. Then applied some filters to extract features from input images, while pooling layers downsample the features to reduce computational complexity. It begins with an overview, detailing the dataset's composition, the CNN architecture employed for classification, and the training and evaluation processes. It also discusses the results obtained from model evaluation and potential usage scenarios. Additionally, I performed some hyperparameter tunning on CNN."
    
  # services
  disable_achievements: false
  achievements:
    - title: Data Analysis
      description: "With the help of PowertBI and python analyze the data of the business or client needs which help them to solve business problems."
      img: /images/da.jpg
    - title: Machine Learning & Deep Learning
      description: "Build various types of ML and DL models according to business or client needs in which it helps to solve complex business issues." 
      img: /images/ml.png
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! 
  email: "paragj30@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
